spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect=org:
          hibernate:
            dialect: MySQL57Dialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: ${SERVER_PORT}
logging:
  config:
    src/main/resources/logback.xml
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org:
      hibernate: INFO

log_context: DEVELOPMENT