spring:
  mail:
    host: ${AWS_HOST}
    port: ${AWS_PORT}
    username: ${AWS_ACCESS}
    password: ${AWS_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-circular-references: true
  profiles:
    active: ${ACTIVE_PROFILE:default}
  aplication:
    name: subsy-saas
  mvc:
    pathmatch.matching-strategy: ant-path-matcher
  jpa:
    show-sql: false
    generate-ddl: true
jwt:
  secret: ${JWT_SECRET}
  expiration: 604800000

#AWS
AWS_ACCESS_KEY: ${AWS_ACCESS}
AWS_SECRET_KEY: ${AWS_SECRET}
EMAIL_SUBSY_AWS: ${EMAIL_AWS}

# ASAAS
URL_ASAAS: {$URL_ASAAS}
TOKEN_ASAAS: {$TOKEN_ASAAS}
TOKEN_WEBHOOK_ASAAS: ${TOKEN_WEBHOOK_ASAAS}

# TAXAS
TAXA_SISTEMA_PERCENTUAL: 0.0
TAXA_SISTEMA_FIXA: 1.49

TAXA_ASAAS_PERCENTUAL_BOLETO: 0.0
TAXA_ASAAS_FIXA_BOLETO: 1.99

TAXA_ASAAS_PERCENTUAL_PIX: 0.0
TAXA_ASAAS_FIXA_PIX: 1.99

TAXA_ASAAS_PERCENTUAL_CARTAO_CREDITO: 2.99
TAXA_ASAAS_FIXA_CARTAO_CREDITO: 0.49