spring:
  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/cobranca-test?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 9081

root_log_level: DEBUG
log_context: TEST