spring:
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: MySQL5InnoDBDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: ${SERVER_PORT}

root_log_level: DEBUG
log_context: DEVELOPMENT