spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: false
        format_sql: false
        dialect=org:
          hibernate:
            dialect: MySQL5InnoDBDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: ${SERVER_PORT}
logging:
  level:
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org:
      hibernate: INFO

log_context: DEVELOPMENT

tuneller.path: ${LOCAL_TUNELLER_PATH}