spring:
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: MySQL5InnoDBDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: ${SERVER_PORT}

root_log_level: INFO
log_context: PRODUCTION