spring:
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: ${JDBC_DATASOURCE_URL}
server:
  port: ${SERVER_PORT}

root_log_level: INFO
log_context: PRODUCTION
